name: Events Demo 1
on: 
  pull_request:
    # specify the activity types of the pull_request event that should trigger the workflow
    types:
      - opened
      - edited
  workflow_dispatch:  # added like this even though we don't have anything to specify below 
  push: 
    # control when the workflow triggers based on an event filter 
    # this one only runs if a push targets the main branch
    branches:
      - main 
      - "dev-*" # covers pushes to example branches like "dev-new", "dev-something"
      - "feat/**" # covers pushes to .. "feat/new", "feat/new/button"...
    paths-ignore:  # this push event will trigger the workflow if one of the above branches are targeted 
    # but we did not change a file in the workflows folder 
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."